### PR TITLE
Nearly-complete support for GtkStatusIcon

### PR DESCRIPTION
**Pull request by amrhassan**

### CODE REVIEW

**Comment by jrick** [comment]
Nice work.  Implementation looks correct, but I have a couple of thoughts on the code style and naming:
1. Please don't use 'this' as a method receiver.  Ideally, receivers should be short and reflect the type of the receiver somehow, but the rest of the codebase just uses 'v' currently, so please stick with that.
2. Use 'p := unsafe.Pointer(thing)' instead of 'pointer := unsafe.Pointer(thing)'
3. By convention, cgo return values should be assigned to the variable named 'c'.
4. By convention, wrapped objects should be named 'obj' rather than 'object'.
5. Please add comments for exported types and functions/methods for godoc.
6. 'GetX11WindowId' should be named 'GetX11WindowID' (ID rather than Id).

The project isn't golint clean but it can be helpful to check the linting for newly added features.

I do understand that all these things can seem nitpicky, but for a large project like this it does help readability substantially when previous coding conventions are followed (even if they were not always the greatest decision at the time; I wish I could go back and make all consts CamelCase, for example).

**Comment by amrhassan** [comment]
No problem. I'll make the required modifications and push them up to this branch pretty soon.

**Comment by amrhassan** [comment]
I think my branch is up to your styling standards now.

**Comment by jrick** [comment]
Merged as 97dc6ef39c9460cd84a71632245f18c558313b1d.

Sorry for the delay.

**Pull request closed without merging**
