### PR TITLE
Added basic TextView support (just constructor so far).

### PR DESCRIPTION
**Pull request by weberc2**
Please leave feedback if you have any. I'm new to git and CGo.

### CODE REVIEW

**Comment by jrick** [comment]
What you have here looks like a good start.  Implement some more TextView functions and I can merge it in.

**Comment by weberc2** [comment]
Please review these changes carefully. I'm not a low-level programmer by nature. I'm learning. You may want to pay careful attention to TextBuffer.GetBounds()

**Comment by weberc2** [comment]
This should be ready for review. I pulled in your upstream changes, which messed up the github diff for the whole pull request, so you'll have to diff manually. Sorry for the inconvenience. Let me know what I can do to improve this.

Thanks.

**Comment by jrick** [comment]
I merged this into Conformal's branch in commit 70587381a0081d13d74ad753f887919856f162ed.  Thanks!

**Pull request closed without merging**
