### PR TITLE
Add GtkBuilder and miscellaneous improvements

### PR DESCRIPTION
**Pull request by dradtke**
The bulk of this pull request is adding some initial support for GtkBuilder, though it's by no means complete. The code I have exists in order to get a basic window with statusbar built in glade to work, but I wanted to see if this approach fit in with how the rest of the library is designed. In particular, how should gtk_builder_get_object() be handled? All native C code uses explicit casting, but I feel like it would make for a cleaner API to have a family of Get() functions rather than make the user cast each returned GObject to something else.

Also of note, the Builder's Add() functions all use GError to capture error messages, which is something I hadn't seen yet in the rest of the library.

### CODE REVIEW

**Comment by dradtke** [comment]
I added a new approach for implementing GetObject(). It's not completely fleshed out, but it seems to work pretty well, and definitely makes it feel more Go-like.

**Comment by jrick** [comment]
I like this approach.  Just need to implement cast() for all the other types too.

I have 2 comments:

1) it would be better to have unexported functions (for example, toWindow(obj _glib.Object) (_Window, error)) to create the composite literal, set the proper ref count, etc.  For objects that we're using embedded structs to satisify GInterfaces, doing the composite literals in cast() will get hairy.

2) The comment about 'is a wrapper around gtk_builder_get_object()' should remain.  Also, it should have an example of returning and type asserting a glib.IObject as another type.

**Comment by dradtke** [comment]
Updated to use a new wrapper function ("toWindow" was already taken, and Go doesn't let you define methods on qualified structs) for Window, both in cast() and in WindowNew(). Also updated the comment for builder.GetObject().

If this looks good, I can work on adding similar methods for the other widgets.

**Comment by dradtke** [comment]
Made some more updates based on your feedback. Let me know what you think.

**Comment by jrick** [comment]
Looks good.  Just need the wrappers for the other types, and I can merge it in.

**Comment by dradtke** [comment]
Added wrappers for the other GTK types. Hopefully I didn't miss or break anything, but it seems to work fine on my computer.

**Comment by kingdonb** [comment]
:+1: I am a novice GTK programmer but this made it possible to follow https://developer.gnome.org/gtk3/3.0/gtk-getting-started.html doc into the final builder example, using gotk3.  Admittedly it was a big help having omnicomplete and syntastic support in YouCompleteMe supporting gocode completion.

**Comment by jrick** [comment]
Thanks for working on this. Just merged all these changes in.

**Pull request closed without merging**
