### PR TITLE
Filled out more of the gtk.Window utility functions

### PR DESCRIPTION
**Pull request by dahenson**
I added a bunch of functions for gtk.Window, trying to follow your structure.  Feel free to critique and give me feedback.

I added TODO's where functions are not implemented in the hopes that I or someone can come back through and add them in the future.

I'm just doing this in my spare time.  I would like to create some examples/tests, and maybe continue on to some of the other structs when I can.

### CODE REVIEW

**Comment by jrick** [comment]
Hi, thanks for your work implementing these functions.  Some comments:

Your comment for SetUrgencyHint has the same comment as for SetSkipPagerHint.

Comments don't end in periods (minor, but clashes with the rest of the package) and are kind of long.  Try to keep under 80 characters?

I'd remove the Get/SetOpacity functions completely, as they are deprecated, instead of just commenting them out.

And finally, I'd remove the SetHasUserRefCount binding.  That function is never meant to be called by users and only exists for some language bindings (we don't need it though, the way we're handing refcounts).

**Comment by dahenson** [comment]
Thanks for your comments, Josh. I was afraid I was way off base, but those
are minor issues I can easily fix. I had meant to take the deprecated
comments out before I pushed, but apparently forgot.

Should I continue to implement the missing functions in the other GTK
elements, or are you not looking for that kind of help right now?

**Comment by jrick** [comment]
If you want to keep working on filling in the extra functions, go ahead, but all these don't have to be committed all at once so if you want to fix up those few things first, that's fine.

Currently, gotk3 is in "good" shape for what Conformal needs it for, and since we're pretty busy with other projects at the moment (one of which is using gotk3), I'm only writing additional function bindings myself if we need it for our project.  However, we welcome the community to keep hacking and adding support for the rest of GTK.  As things settle down, I may continue filling in the rest of the bindings.

**Comment by raichu** [comment]
> Currently, gotk3 is in "good" shape for what Conformal needs it for, and since we're pretty busy with other projects at the moment (one of which is using gotk3), I'm only writing additional function bindings myself if we need it for our project. 

Well, that sounds a bit selfish and anti-community :P

Does this mean we need to wait indefinitely for a pull request to be mainlined?

**Comment by raichu** [comment]
I just checked the network, and there're already various forks with new stuff added. From my experience this kind of stalling attitude will cause either fragmentation and bunch of wasted efforts + obsolete main repo + duplicate efforts or a brand new fork with an appetite to merging good stuff around. I understand you being busy with other stuff, but this is a pull request (=code already written) we're talking about here. Please review and reject/accept them ---you can do this while eating sandwiches :)

**Comment by dahenson** [comment]
Josh was very clear about what needs to be fixed in my pull request, I just
haven't had a chance to commit those fixes.

No need to get your panties in a bunch.

**Comment by raichu** [comment]
Not everything is about you.
Anyway, the only thing he wasn't very clear about was whether they will be merged soon or not. I hope I totally got the wrong impression.

**Comment by jrick** [comment]
Alright guys, some history on the project.

gotk3 was originally written because conformal wanted a decent GUI toolkit for our bitcoin work.  We looked at alternatives, and didn't find anything we liked, so we rolled our own with the specific purpose of using it with out bitcoin client.

It's not my intention to keep pull requests sitting here forever, but as we are busy with other said projects, and we hope to keep the gotk3 code very high quality, reviewing and merging can take a bit more time than I wished it did.

I'll try to spend some more time devoted to these pull requests, but my primary focus still needs to remain on other projects at the moment.

**Comment by dahenson** [comment]
Raichu,
thank you for putting me in my place.  Clearly I needed it as I was getting out of hand.

Thanks for the history, Josh.  I had gleaned that much from just looking at the conformal projects here on github, and from reading the README.md file.

I noticed that even the simplest programs get compiled into a (relatively) monstrous executable.  Do you think that will ever be optimized, or is it just a limitation of binding C to Go?

**Comment by davecgh** [comment]
I suspect you're seeing the Go runtime.  All Go executables require it, so they will always be at least that size.

For example, even the simplest possible Go program:

``` Go
package main
func main() {
}
```

Compiles to:

``` bash
-rwxr-xr-x    1 davec    davec     373k Sep 12 11:11 foo.exe
```

EDIT:

I should also add that Go statically links all deps, so if you're comparing against something that is linking against shared libs, that would cause a pretty large difference in size too.

**Comment by dahenson** [comment]
Josh, I was going through some of these changes and I was wondering what you meant by not having periods at the end of a comment.  I skipped around, and the rest of the gtk.go file has plenty of comments with periods at the end.  I don't mind removing them, but I don't see how it clashes with the rest of the package.

Mind you, this is not a huge issue.  Just checking with home base.

**Comment by jrick** [comment]
Oh, I had meant to say that the comments in the additions you made didn't end in periods.  Sorry about that, I see that you just removed some periods with your latest change.  Yeah it's minor, but consistency == good. :/

**Comment by weberc2** [comment]
Has this been mainlined yet? Sincere question--I'm still trying to get the hang of github.

**Comment by dahenson** [comment]
As stated elsewhere: nope. Not a thing has changed.

**Comment by jrick** [comment]
I've merged this into Conformal's branch in commit 91cb49a651bdd81560781db3848813f738239817. Thanks!

**Pull request closed without merging**
