### PR TITLE
Implement GtkCellRendererToggle

### PR DESCRIPTION
**Pull request by weberc2**
Implements GtkCellRendererToggle and all methods.

### CODE REVIEW

**Comment by weberc2** [comment]
@jrick Could you take a look at this soon? I'm still a little fuzzy on Github pull requests, but I think the code is good. Please advise.

Thanks,
Craig

**Comment by jrick** [comment]
Hi,

Your fork has diverged from Conformal's repo (this is mostly due to company policy, we have to squash and rebase so master has a linear history).  Could you update the patch so it builds with latest our latest code?  There are some nice goodies in there too that you'd probably want too. :)

**Comment by weberc2** [comment]
Sure, I'm still learning git so let me make sure I understand you: I should effectively pull your changes (conformal fork) into my pull request and resubmit?

**Comment by jrick** [comment]
Since I think github lets you submit pull requests for feature branches, it would probably be easiest to pull conformal master into another branch in your repo, and squash+cherrypick the changes you want pulled.  That way I can easily do a fast-forward merge.

**Comment by weberc2** [comment]
I haven't squashed yet (I'm not very confident in git and it took me a long time to get the merge right). If you feel strongly about it, I can make an attempt, otherwise I think my fork should be ready.

**Pull request closed without merging**
